 BULLETTRAIN_PROMPT_ORDER=(
    status
    custom
    context
    dir
    perl
    ruby
    virtualenv
    nvm
    go
    git
#    hg
#    cmd_exec_time
  )
BULLETTRAIN_PROMPT_SEPARATE_LINE=false
BULLETTRAIN_PROMPT_ADD_NEWLINE=false
BULLETTRAIN_STATUS_SHOW=false
BULLETTRAIN_DIR_EXTENDED=2
BULLETTRAIN_DIR_BG='NONE'
BULLETTRAIN_DIR_FG=63
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_GIT_COLORIZE_DIRTY_BG_COLOR='NONE'
BULLETTRAIN_GIT_COLORIZE_DIRTY_FG_COLOR=82
BULLETTRAIN_GIT_BG=black
BULLETTRAIN_GIT_FG=82
BULLETTRAIN_GIT_EXTENDED=false
BULLETTRAIN_GIT_PREFIX=""
BULLETTRAIN_GIT_SUFFIX=""
BULLETTRAIN_GIT_CLEAN=""
BULLETTRAIN_GIT_DIRTY="!"

BULLETTRAIN_HG_SHOW=false
BULLETTRAIN_RUBY_SHOW=true
BULLETTRAIN_RUBY_BG='NONE'
BULLETTRAIN_RUBY_FG=240
BULLETTRAIN_RUBY_PREFIX=""

BULLETTRAIN_PERL_SHOW=false
BULLETTRAIN_GO_SHOW=true
BULLETTRAIN_GO_BG=black

BULLETTRAIN_VIRTUALENV_SHOW=false

